logo:
  subtitle: 'Look at the code, you are still here | Always alive for 30 years.'
  menubar:
  columns: 2
  items: 
  - id: post
   theme: '#1BCDFC'
   icon: solar:documents-bold-duotone
   title: Blog
  - id: social
   theme: '#F44336'
   icon: solar:chat-square-like-bold-duotone
   title: Social medias
   url: /friends/
