logo:
  subtitle: 'Look at the code, you are still here | Always alive for 30 years.'
menubar:
  columns: 2
  items:
      - id: post # 页面中高亮的 menu_id
        theme: '#1BCDFC' # 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
        icon: solar:documents-bold-duotone # 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
        title: Articles # 标题
        url: / # 跳转链接，支持相对路径和绝对路径
      - id: social
        theme: '#F44336'
        icon: solar:chat-square-like-bold-duotone
        title: Social medias
        url: /friends/
